"""rename_rerank_model_type_to_provider

Revision ID: 0d05ffe676a0
Revises: e63d93c3f9e2
Create Date: 2026-03-31 15:33:11.598059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d05ffe676a0'
down_revision: Union[str, Sequence[str], None] = 'e63d93c3f9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add provider column as nullable first (MySQL requires this for NOT NULL columns with existing data)
    op.add_column('rerank_models', sa.Column('provider', sa.String(length=50), nullable=True))
    # Copy existing type values to provider for all rows
    op.execute("UPDATE rerank_models SET provider = type WHERE provider IS NULL")
    # Set default for existing rows that might still be null
    op.execute("UPDATE rerank_models SET provider = 'openai_compatible' WHERE provider IS NULL")
    # Alter to NOT NULL using MySQL-compatible MODIFY COLUMN with full type
    op.execute(
        "ALTER TABLE rerank_models MODIFY COLUMN provider VARCHAR(50) NOT NULL"
    )
    # Drop the old type column
    op.drop_column('rerank_models', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rerank_models', sa.Column('type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.drop_column('rerank_models', 'provider')
    # ### end Alembic commands ###
