"""init

Revision ID: b96bcc268480
Revises: 
Create Date: 2026-03-29 16:56:25.777987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b96bcc268480'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('local_model_path', sa.String(length=500), nullable=True),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_embedding_models_user_id'), 'embedding_models', ['user_id'], unique=False)
    op.create_table('llm_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('context_window', sa.Integer(), nullable=False),
    sa.Column('support_vision', sa.Boolean(), nullable=False),
    sa.Column('support_function_calling', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_models_user_id'), 'llm_models', ['user_id'], unique=False)
    op.create_table('rerank_models',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('encrypted_api_key', sa.Text(), nullable=True),
    sa.Column('top_n', sa.Integer(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rerank_models_user_id'), 'rerank_models', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='⽤户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='⽤户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码（加密存储）'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='头像URL'),
    sa.Column('gender', sa.Enum('male', 'female', 'unknown'), nullable=True, comment='性别'),
    sa.Column('bio', sa.String(length=500), nullable=True, comment='个⼈简介'),
    sa.Column('is_email_verified', sa.Boolean(), server_default='0', nullable=False, comment='邮箱是否已验证'),
    sa.Column('is_phone_verified', sa.Boolean(), server_default='0', nullable=False, comment='手机号是否已验证'),
    sa.Column('is_superuser', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_email', 'user', ['email'], unique=True)
    op.create_index('idx_phone', 'user', ['phone'], unique=True)
    op.create_index('idx_username', 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_username', table_name='user')
    op.drop_index('idx_phone', table_name='user')
    op.drop_index('idx_email', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rerank_models_user_id'), table_name='rerank_models')
    op.drop_table('rerank_models')
    op.drop_index(op.f('ix_llm_models_user_id'), table_name='llm_models')
    op.drop_table('llm_models')
    op.drop_index(op.f('ix_embedding_models_user_id'), table_name='embedding_models')
    op.drop_table('embedding_models')
    # ### end Alembic commands ###
