"""add_knowledge_base_tables

Revision ID: e63d93c3f9e2
Revises: b96bcc268480
Create Date: 2026-03-31 00:43:14.011860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63d93c3f9e2'
down_revision: Union[str, Sequence[str], None] = 'b96bcc268480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_documents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_model_id', sa.String(length=64), nullable=True),
    sa.Column('rerank_model_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('chunk_mode', sa.String(length=50), nullable=False),
    sa.Column('retrieval_mode', sa.String(length=20), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('similarity_threshold', sa.Float(), nullable=False),
    sa.Column('vector_weight', sa.Float(), nullable=False),
    sa.Column('enable_rerank', sa.Boolean(), nullable=False),
    sa.Column('rerank_top_k', sa.Integer(), nullable=False),
    sa.Column('collection_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['embedding_model_id'], ['llm_models.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rerank_model_id'], ['rerank_models.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_documents_user_id'), 'kb_documents', ['user_id'], unique=False)
    op.create_table('kb_files',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.String(length=64), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('file_md5', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('file_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kb_id'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_files_kb_id'), 'kb_files', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_files_user_id'), 'kb_files', ['user_id'], unique=False)
    op.create_table('kb_chunks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kb_id', sa.String(length=64), nullable=False),
    sa.Column('file_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['kb_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kb_id'], ['kb_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_chunks_file_id'), 'kb_chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_kb_id'), 'kb_chunks', ['kb_id'], unique=False)
    op.create_index(op.f('ix_kb_chunks_user_id'), 'kb_chunks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_chunks_user_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_kb_id'), table_name='kb_chunks')
    op.drop_index(op.f('ix_kb_chunks_file_id'), table_name='kb_chunks')
    op.drop_table('kb_chunks')
    op.drop_index(op.f('ix_kb_files_user_id'), table_name='kb_files')
    op.drop_index(op.f('ix_kb_files_kb_id'), table_name='kb_files')
    op.drop_table('kb_files')
    op.drop_index(op.f('ix_kb_documents_user_id'), table_name='kb_documents')
    op.drop_table('kb_documents')
    # ### end Alembic commands ###
